# Generated by Django 6.0.3 on 2026-03-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaultReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('water', 'Water/Burst Pipe'), ('elec', 'Electricity Outage'), ('road', 'Pothole/Roads'), ('lights', 'Streetlights')], max_length=20)),
                ('description', models.TextField()),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lng', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending (Red)'), ('assigned', 'Assigned (Orange)'), ('resolved', 'Resolved (Green)')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
