# Generated by Django 6.0.3 on 2026-04-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faultreport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fault_photos/'),
        ),
    ]
